'use client'
import { Msg, Avatar, when } from '@/lib/client-utils'
import { Icon } from './Icon'
export function ConversationList({ messages, activeFolder, selUid, listLoading, folderTitle, onOpen, onRefresh, onDelete, deleting, hasMore, loadingMore, onLoadMore, search, onSearch, error, desktop, onDownload, downloading }: {
  messages: Msg[]; activeFolder: string; selUid: number | null; listLoading: boolean; folderTitle: string; onOpen: (uid: number) => void; onRefresh: () => void; onDelete: (uid: number) => void; deleting: boolean; hasMore?: boolean; loadingMore?: boolean; onLoadMore?: () => void; search: string; onSearch: (v: string) => void; error: string; desktop: boolean; onDownload: () => void; downloading: boolean
}) {
  const outgoing = ['sent', 'drafts', 'local-drafts'].includes(activeFolder)
  return <section className="conversation-column"><div className="conversation-heading"><div><p className="sidebar-label">YOUR MESSAGES</p><h1>{folderTitle}<span>{messages.length}</span></h1></div><button className="icon-button" aria-label="Refresh mailbox" onClick={onRefresh}><Icon name="refresh" /></button></div><div className="conversation-tools"><label className="mobile-mail-search md:hidden"><Icon name="search" size={16} /><input value={search} onChange={e => onSearch(e.target.value)} aria-label="Search this folder on mobile" placeholder="Search this folder" /></label>{desktop && activeFolder !== 'local-drafts' && <button onClick={onDownload} disabled={downloading || !messages.length} className="download-folder"><Icon name="download" size={14} />{downloading ? 'Downloading mail…' : 'Download for offline'}</button>}</div>
    {error && <div className="mail-inline-error" role="status">{error}</div>}
    <div className="conversation-scroll">{listLoading && <div className="list-state">Refreshing your mailbox…</div>}{!listLoading && messages.length === 0 && <div className="list-state"><Icon name={search ? 'search' : 'inbox'} size={30} /><h2>{search ? 'No matching messages' : 'No messages to show'}</h2><p>{search ? 'Try another sender or subject.' : error ? 'Reconnect and refresh to load this folder.' : 'Messages in this folder will appear here.'}</p></div>}
      {messages.map(message => <div key={message.uid} data-testid="conversation-card" className={'conversation-row ' + (selUid === message.uid ? 'is-selected' : '') + (!message.seen ? ' is-unread' : '')}>
        <button className="conversation-open" onClick={() => onOpen(message.uid)}><Avatar name={outgoing ? message.to || 'Draft' : message.fromName || message.from} cls="w-9 h-9 rounded-xl" /><span className="conversation-copy"><span className="conversation-sender"><strong>{outgoing ? 'To: ' + (message.to || 'Not addressed') : message.fromName || message.from}</strong><time>{when(message.date)}</time></span><span className="conversation-subject">{message.flagged && <Icon name="star" size={13} />}{message.subject}</span>{!message.seen && <span className="unread-dot" />}</span></button><button className="conversation-delete" data-testid="row-delete-button" aria-label={`Delete ${message.subject}`} onClick={() => onDelete(message.uid)} disabled={deleting}><Icon name="trash" size={14} /></button></div>)}
      {hasMore && !listLoading && <button className="load-more" onClick={onLoadMore} disabled={loadingMore}>{loadingMore ? 'Loading…' : 'Load older messages'}</button>}
    </div>
  </section>
}
