'use client'
import { Mark } from '@/lib/client-utils'
import { SignInForm } from './SignIn'
import { Icon } from './Icon'
const releases='https://github.com/zeroai-tech/zaim/releases'
export function Landing({ onSignIn, onStart, authOpen, closeAuth, onDone }: { onSignIn:()=>void; onStart:()=>void; authOpen:boolean; closeAuth:()=>void; onDone:()=>void }) {
  return <main className="landing-container"><header className="landing-header"><div className="mail-brand"><Mark/><span>Zaim<span className="brand-byline">by ZeroAI</span></span></div><div className="flex gap-4 items-center"><a className="text-xs text-[color:var(--muted)] hidden sm:block" href="https://github.com/zeroai-tech/zaim" target="_blank" rel="noopener noreferrer">Documentation</a><button className="secondary-button" onClick={onSignIn}>Sign in</button></div></header><section className="landing-hero"><div><p className="eyebrow">MAIL FOR PEOPLE. TOOLS FOR AGENTS.</p><h1>Your work begins<br />with a conversation.<br /><span>Make room for it.</span></h1><p>A focused inbox for people and their AI agents. Read, write, and organize your email in the browser or on your desktop.</p><div className="flex flex-wrap gap-3"><button className="primary-button" onClick={onStart}>Open your mailbox<Icon name="sent" size={16}/></button><a className="secondary-button" href="#desktop">Get the desktop app<Icon name="download" size={16}/></a></div><p className="!text-xs">Built by <a href="https://zeroaitech.tech" className="text-[color:var(--accent)]">ZeroAI Technologies</a>. Connect your existing mailbox.</p></div><div className="signin-card" id="signin"><div className="eyebrow mb-5">YOUR MAILBOX, READY WHEN YOU ARE</div><h2>Welcome to Zaim.</h2><p>Sign in with your email address and mailbox password. Your mail stays with your provider.</p><SignInForm onDone={onDone}/><div className="flex items-center gap-2 text-[10px] text-[color:var(--muted)] mt-6"><Icon name="lock" size={13}/>Credentials are sealed in an encrypted session.</div></div></section><section className="landing-features">{[
    { icon:'inbox' as const,title:'A calmer inbox.',body:'A focused reading space, clear folders, quick search, and a composer that keeps your conversation in view.' },
    { icon:'download' as const,title:'Work through the interruption.',body:'The desktop app keeps downloaded mail and attachments on your device. Write and save drafts without a connection; send when you reconnect.' },
    { icon:'bot' as const,title:'Give your agents the right tools.',body:'CLI, MCP, and API access connect your mailbox to agent workflows. Keep control of the account and credentials you choose to share.' },
  ].map(feature=><article key={feature.title}><Icon name={feature.icon} size={25} className="text-[color:var(--accent)]"/><h2>{feature.title}</h2><p>{feature.body}</p></article>)}</section><section className="landing-download" id="desktop"><div><p className="eyebrow">DESKTOP / WEB / CLI / MCP</p><h2 className="mt-3">Your mailbox. On your machine.</h2><p>Available desktop releases and installation instructions are on GitHub.<br/>First-time mailbox sign-in and sending require an internet connection.</p></div><div className="landing-download-links"><a href={releases} target="_blank" rel="noopener noreferrer" className="primary-button">Desktop downloads<Icon name="download" size={16}/></a><a href="https://github.com/zeroai-tech/zaim#the-agent--cli-surface" target="_blank" rel="noopener noreferrer" className="secondary-button">CLI & agent setup</a></div></section><footer className="py-7 border-t text-[11px] text-[color:var(--muted)] flex justify-between gap-6 flex-wrap"><span>Zaim by ZeroAI Technologies</span><a href="https://zeroaitech.tech/privacy">Company privacy information</a></footer></main>
}
