'use client'
import { useEffect, useState } from 'react'
import { ComposeInit, Full, Folder, Avatar, fmtSize, q, linkifyText } from '@/lib/client-utils'
import { Compose } from './Compose'
import { Icon } from './Icon'
export function ReadingCanvas({ sel, selUid, activeFolder, folders, activeAccount, loadingDraft, onEditDraft, deleting, onDelete, onReply, compose, from, account, onComposeClose, onComposeSent, onBack, desktop, offline, error }: {
  sel:Full|null; selUid:number|null; activeFolder:string; folders:Folder[]; activeAccount:string; loadingDraft:boolean; onEditDraft:()=>void; deleting:boolean; onDelete:()=>void; onReply:()=>void; compose:ComposeInit|null; from?:string; account:string; onComposeClose:()=>void; onComposeSent:()=>void; onBack:()=>void; desktop:boolean; offline:boolean; error:string
}) {
  const [remoteImages,setRemoteImages]=useState(false)
  useEffect(()=>setRemoteImages(false),[selUid,activeAccount])
  if(compose) return <Compose key={compose.localDraftId || compose.draft?.uid || `${account}:${compose.to}:${compose.subject}`} initial={compose} from={from} account={account} onClose={onComposeClose} onSent={onComposeSent} desktop={desktop} offline={offline} />
  if(!sel) return <div className="reader-empty"><div><div className="empty-icon"><Icon name={error?'warning':'inbox'} size={36}/></div><h2>{error?'Message unavailable':selUid!=null?'Opening your message…':'A little room to focus.'}</h2><p>{error || 'Choose a conversation. Read, reply, and keep your work moving.'}</p>{selUid!=null && <button className="secondary-button" onClick={onBack}>Back to mailbox</button>}<small>{!error && 'Zaim / Your mail, thoughtfully organized.'}</small></div></div>
  return <article className="mail-reader"><div className="reader-toolbar"><button className="md:hidden" aria-label="Back to mailbox" onClick={onBack}><Icon name="back" />Mail</button>{['drafts','local-drafts'].includes(activeFolder)?<button disabled={loadingDraft} onClick={onEditDraft}><Icon name="compose" />{loadingDraft?'Loading…':'Edit draft'}</button>:<button data-testid="reply-button" onClick={onReply}><Icon name="reply" />Reply</button>}<button data-testid="delete-button" disabled={deleting || (offline && activeFolder!=='local-drafts')} onClick={onDelete}><Icon name="trash" />{deleting?'Deleting…':'Delete'}</button><span className="ml-auto text-[10px] text-[color:var(--muted)] hidden sm:inline">{activeFolder==='local-drafts'?'Saved on this device':offline?'Cached copy':'Conversation'}</span></div>
    <div className="reader-content"><h2>{sel.subject}</h2><div className="reader-sender"><Avatar name={sel.fromName||sel.from||'Local draft'} cls="w-10 h-10 rounded-xl"/><div className="min-w-0"><strong>{sel.fromName||sel.from||'Local draft'}</strong><p>{sel.from} · to {sel.to||'Not addressed'}</p></div><time>{new Date(sel.date).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</time></div>
      {!!sel.attachments?.length && <div className="flex gap-2 flex-wrap mt-5">{sel.attachments.map((att,index)=><a key={index} className="mail-attachment" download href={'/api/mail/attachment'+q({uid:String(sel.uid),mailbox:folders.find(f=>f.key===activeFolder)?.path||'INBOX',index:String(index),account:activeAccount,offline:offline?'1':undefined})}><Icon name="attach" size={14}/><span>{att.filename}</span><span className="text-[color:var(--muted)]">{fmtSize(att.size)}</span></a>)}</div>}
      <div className="flex items-center justify-between mt-6 mb-3 text-[10px] text-[color:var(--muted)]"><span>External images are {remoteImages?'enabled':'blocked'}.</span>{!offline && <button className="text-[color:var(--accent)]" onClick={()=>setRemoteImages(!remoteImages)}>{remoteImages?'Block external images':'Load external images'}</button>}</div>
      <iframe title="Message content" sandbox="allow-popups allow-popups-to-escape-sandbox" className="w-full bg-white rounded-lg" style={{height:'min(65vh,650px)',border:'1px solid var(--line)'}} srcDoc={`<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data: cid: ${remoteImages?'https:':''}; font-src data:; base-uri 'none'; form-action 'none'"><base target="_blank"></head><body style="margin:0;padding:24px;font-family:system-ui;font-size:14px;line-height:1.8;color:#172338;overflow-wrap:anywhere">${sel.html || `<pre style="font:inherit;white-space:pre-wrap;margin:0">${linkifyText(sel.text||'')}</pre>`}</body></html>`}/>
    </div>
  </article>
}
